---
- name: Enforce VLAN Source of Truth
  hosts: switches
  gather_facts: no

  vars_files:
    - ../group_vars/switches/vlans.yml

  tasks:
    - name: Enforce VLANs from source of truth
      cisco.ios.ios_vlans:
        config: "{{ vlans }}"
        state: replaced

    - name: Confirm applied VLANs
      cisco.ios.ios_facts:
        gather_subset: all
        gather_network_resources:
          - vlans

    - name: Display configured VLANs
      ansible.builtin.debug:
        msg: "{{ ansible_network_resources.vlans }}"

    - name: Save configuration
      cisco.ios.ios_config:
        save_when: modified
